"""Provider-neutral Generation contracts and provider-specific adapters.

Generation consumes Evidence Packets but owns neither Retrieval nor Evidence
Assembly policy.  Provider-neutral use keeps an injected transport boundary;
the first scoped Bailian adapter also exposes its explicitly authorized live
HTTP transport.
"""

from .generation import (
    BASELINE_QWEN_MODEL_ID,
    DEFAULT_GENERATION_INSTRUCTION,
    EXACT_SNAPSHOT_POLICY,
    GENERATION_PROVIDER_ID_BAILIAN,
    GENERATION_REQUEST_SCHEMA_VERSION,
    GENERATION_RESULT_SCHEMA_VERSION,
    SEMANTIC_FAITHFULNESS_NOT_EVALUATED,
    BailianControlConfig,
    BailianGenerationProvider,
    BailianOpenAICompatibleTransport,
    BailianTransport,
    BailianTransportError,
    BailianTransportResponse,
    CitationCoveragePolicy,
    CitationValidation,
    GenerationConfigurationError,
    GenerationContractError,
    GenerationEvidence,
    GenerationInstruction,
    GenerationProvider,
    GenerationRequest,
    GenerationResult,
    DEFAULT_G2_SMOKE_PACKET,
    generation_result_json_bytes,
    project_generation_request,
    run_bailian_control_smoke,
    validate_citations,
    workspace_from_bailian_base_url,
    write_generation_result,
)
from .measure import (
    DEFAULT_M1_ACCEPTED_INPUT,
    DEFAULT_M1_BASELINE_ROOT,
    DEFAULT_M1_MODEL_DIR,
    DEFAULT_M1_RUNTIME_ROOT,
    M1_PROVIDER_ATTEMPT_BUDGET,
    M1_QUESTION_COUNT,
    M1_SCHEMA_VERSION,
    AcceptedQuestion,
    M1Baseline,
    M1MeasureError,
    load_accepted_questions,
    preflight_m1,
    run_m1_measure,
    write_question_packets,
)

__all__ = [
    "BASELINE_QWEN_MODEL_ID",
    "DEFAULT_GENERATION_INSTRUCTION",
    "EXACT_SNAPSHOT_POLICY",
    "GENERATION_PROVIDER_ID_BAILIAN",
    "GENERATION_REQUEST_SCHEMA_VERSION",
    "GENERATION_RESULT_SCHEMA_VERSION",
    "SEMANTIC_FAITHFULNESS_NOT_EVALUATED",
    "BailianControlConfig",
    "BailianGenerationProvider",
    "BailianOpenAICompatibleTransport",
    "BailianTransport",
    "BailianTransportError",
    "BailianTransportResponse",
    "CitationCoveragePolicy",
    "CitationValidation",
    "GenerationConfigurationError",
    "GenerationContractError",
    "GenerationEvidence",
    "GenerationInstruction",
    "GenerationProvider",
    "GenerationRequest",
    "GenerationResult",
    "DEFAULT_G2_SMOKE_PACKET",
    "generation_result_json_bytes",
    "project_generation_request",
    "run_bailian_control_smoke",
    "validate_citations",
    "workspace_from_bailian_base_url",
    "write_generation_result",
    "DEFAULT_M1_ACCEPTED_INPUT",
    "DEFAULT_M1_BASELINE_ROOT",
    "DEFAULT_M1_MODEL_DIR",
    "DEFAULT_M1_RUNTIME_ROOT",
    "M1_PROVIDER_ATTEMPT_BUDGET",
    "M1_QUESTION_COUNT",
    "M1_SCHEMA_VERSION",
    "AcceptedQuestion",
    "M1Baseline",
    "M1MeasureError",
    "load_accepted_questions",
    "preflight_m1",
    "run_m1_measure",
    "write_question_packets",
]
