"""Phase 04 Retrieval and deterministic Evidence Assembly.

The package contains the P04-RAG-W1 Retrieval Unit and candidate-neutral
Evidence Assembly core, plus the P04-RAG-W2 versioned lexical, local Dense,
and deterministic Hybrid candidate-retrieval baseline.  Generation is a
separate package that consumes Evidence Packets through their public contract.
"""

from .benchmark import (
    BENCHMARK_SCHEMA_VERSION,
    BenchmarkValidationError,
    load_benchmark,
    resolve_benchmark_locations,
    validate_benchmark,
)
from .profiler import (
    CORPUS_PROFILE_VERSION,
    CanonicalProfileError,
    profile_canonical_run,
)
from .representations import (
    REPRESENTATION_ARMS,
    RETRIEVAL_DOCUMENT_SCHEMA_VERSION,
    RETRIEVAL_REPRESENTATION_VERSION,
    RetrievalRepresentationError,
    build_retrieval_documents,
    document_covers_location,
    load_retrieval_documents,
)
from .lexical import LEXICAL_BIGRAM_ANALYZER_VERSION, LEXICAL_SCORER_VERSION
from .retrieval_units import (
    IDENTITY_ADDRESS_POLICY_VERSION,
    RETRIEVAL_UNIT_BUILD_SCHEMA_VERSION,
    RETRIEVAL_UNIT_GENERATOR_VERSION,
    RETRIEVAL_UNIT_SCHEMA_VERSION,
    RetrievalUnitBuildConfig,
    RetrievalUnitError,
    build_retrieval_units,
    load_retrieval_units,
)
from .evidence_assembly import (
    EVIDENCE_ASSEMBLY_VERSION,
    EVIDENCE_PACKET_SCHEMA_VERSION,
    EvidenceAssemblyConfig,
    EvidenceAssemblyDiagnostics,
    EvidenceAssemblyError,
    PreparedAssemblyContext,
    assemble_evidence_packet,
    evidence_packet_json_bytes,
    evidence_packet_markdown,
    prepare_evidence_assembly_context,
    render_evidence_packet,
    write_evidence_packet,
)
from .candidate_retrieval import (
    CANDIDATE_SCHEMA_VERSION,
    DENSE_INDEX_SCHEMA_VERSION,
    LEXICAL_INDEX_SCHEMA_VERSION,
    RRF_FUSION_VERSION,
    CandidateBundle,
    CandidateRetrievalError,
    build_dense_index,
    build_lexical_index,
    dense_candidates,
    dense_candidates_local,
    encode_dense_query,
    hybrid_candidates,
    lexical_candidates,
    retrieve_candidates,
)
from .production_materialization import (
    PINNED_BGE_SMALL_MODEL_SHA256,
    ProductionMaterializationError,
    materialize_production,
    preflight_production_inputs,
)

__all__ = [
    "BENCHMARK_SCHEMA_VERSION",
    "BenchmarkValidationError",
    "CORPUS_PROFILE_VERSION",
    "CanonicalProfileError",
    "load_benchmark",
    "profile_canonical_run",
    "REPRESENTATION_ARMS",
    "RETRIEVAL_DOCUMENT_SCHEMA_VERSION",
    "RETRIEVAL_REPRESENTATION_VERSION",
    "RetrievalRepresentationError",
    "build_retrieval_documents",
    "document_covers_location",
    "load_retrieval_documents",
    "LEXICAL_BIGRAM_ANALYZER_VERSION",
    "LEXICAL_SCORER_VERSION",
    "IDENTITY_ADDRESS_POLICY_VERSION",
    "RETRIEVAL_UNIT_BUILD_SCHEMA_VERSION",
    "RETRIEVAL_UNIT_GENERATOR_VERSION",
    "RETRIEVAL_UNIT_SCHEMA_VERSION",
    "RetrievalUnitBuildConfig",
    "RetrievalUnitError",
    "build_retrieval_units",
    "load_retrieval_units",
    "EVIDENCE_ASSEMBLY_VERSION",
    "EVIDENCE_PACKET_SCHEMA_VERSION",
    "EvidenceAssemblyConfig",
    "EvidenceAssemblyDiagnostics",
    "EvidenceAssemblyError",
    "PreparedAssemblyContext",
    "assemble_evidence_packet",
    "evidence_packet_json_bytes",
    "evidence_packet_markdown",
    "prepare_evidence_assembly_context",
    "render_evidence_packet",
    "write_evidence_packet",
    "CANDIDATE_SCHEMA_VERSION",
    "DENSE_INDEX_SCHEMA_VERSION",
    "LEXICAL_INDEX_SCHEMA_VERSION",
    "RRF_FUSION_VERSION",
    "CandidateBundle",
    "CandidateRetrievalError",
    "build_dense_index",
    "build_lexical_index",
    "dense_candidates",
    "dense_candidates_local",
    "encode_dense_query",
    "hybrid_candidates",
    "lexical_candidates",
    "retrieve_candidates",
    "PINNED_BGE_SMALL_MODEL_SHA256",
    "ProductionMaterializationError",
    "materialize_production",
    "preflight_production_inputs",
    "resolve_benchmark_locations",
    "validate_benchmark",
]
