"""Provider-neutral single-question RAG orchestration."""

from .backend import (
    PreparedRagState,
    SingleQuestionBackendConfig,
    RagBackendPreparationError,
    prepare_rag_state,
    run_single_question,
)
from .adaptive import (
    ADAPTIVE_RESULT_SCHEMA_VERSION,
    ASSESSMENT_REQUEST_SCHEMA_VERSION,
    ASSESSMENT_RESULT_SCHEMA_VERSION,
    ONE_SLOT_ADMISSION_POLICY,
    AdaptiveContractError,
    AnswerDisposition,
    BlockAEvidenceCapability,
    EvidenceAssessmentRequest,
    EvidenceAssessmentResult,
    EvidenceAssessor,
    EvidenceCondition,
    FrozenBlockAEvidenceCapability,
    OrchestrationAction,
    PacketBinding,
    bind_evidence_packet,
    run_bounded_adaptive_question,
)
from .config import (
    DEFAULT_PRODUCTION_FIELD_AWARE_LEXICAL_MANIFEST,
    DEFAULT_PRODUCTION_QWEN_DENSE_MANIFEST,
    DEFAULT_PRODUCTION_QWEN_RERANK_ENDPOINT,
    DEFAULT_PRODUCTION_QWEN_RERANK_WORKSPACE,
    DEFAULT_PRODUCTION_RAG_ROOT,
    ProductionRagArtifactPaths,
)

__all__ = [
    "ADAPTIVE_RESULT_SCHEMA_VERSION",
    "ASSESSMENT_REQUEST_SCHEMA_VERSION",
    "ASSESSMENT_RESULT_SCHEMA_VERSION",
    "ONE_SLOT_ADMISSION_POLICY",
    "AdaptiveContractError",
    "AnswerDisposition",
    "BlockAEvidenceCapability",
    "EvidenceAssessmentRequest",
    "EvidenceAssessmentResult",
    "EvidenceAssessor",
    "EvidenceCondition",
    "FrozenBlockAEvidenceCapability",
    "OrchestrationAction",
    "PacketBinding",
    "PreparedRagState",
    "SingleQuestionBackendConfig",
    "RagBackendPreparationError",
    "prepare_rag_state",
    "bind_evidence_packet",
    "run_bounded_adaptive_question",
    "run_single_question",
    "DEFAULT_PRODUCTION_QWEN_DENSE_MANIFEST",
    "DEFAULT_PRODUCTION_FIELD_AWARE_LEXICAL_MANIFEST",
    "DEFAULT_PRODUCTION_QWEN_RERANK_ENDPOINT",
    "DEFAULT_PRODUCTION_QWEN_RERANK_WORKSPACE",
    "DEFAULT_PRODUCTION_RAG_ROOT",
    "ProductionRagArtifactPaths",
]
